test.db1:
    schema: water
    jdbcUrl: jdbc:mysql://localhost:3306/water?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
